### ISSUE TITLE
Allow `pathStyle` to be overridable?

### ISSUE THREAD

**Issue by cheapsteak** [react-component/progress#36] opened 2017-10-08 23:50 UTC
Currently can't easily override this - `stroke-dashoffset 0.3s ease 0s, stroke 0.3s linear`
Would be good to be able to provide our own

**Comment by xrkffgg** [comment] 2020-11-16 10:05
Duplicate of https://github.com/react-component/progress/issues/5

**Closed by xrkffgg** 2020-11-16 10:05 UTC
